# Sources:
# * https://alexw.co.uk/blog-posts/docker/docker-compose/2021/04/16/grafana-docker-mysql.html
# * https://github.com/coder-society/nodejs-application-monitoring-with-prometheus-and-grafana
# * https://grafana.com/grafana/dashboards/893-main/
---
version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.40.1
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    restart: always
    volumes:
      - ./grafana:/etc/grafana/provisioning
    ports:
      - 3000:3000

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080      

  primes-nodejs:
    image: ariel17/primes
    container_name: primes
    restart: always
    ports:
      - 8090:8080
