# Sources:
# * https://alexw.co.uk/blog-posts/docker/docker-compose/2021/04/16/grafana-docker-mysql.html
# * https://github.com/coder-society/nodejs-application-monitoring-with-prometheus-and-grafana
---
version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.40.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning
    environment:
      - GF_DATABASE_HOST=grafana_db:3306
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=password
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_MAX_OPEN_CONN=300
    ports:
      - 3000:3000
    links:
      - grafana_db:grafana_db
    depends_on:
      - grafana_db

  grafana_db:
    image: mysql:5.6
    container_name: grafana_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: grafana
      MYSQL_USER: grafana
      MYSQL_PASSWORD: password
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --innodb_monitor_enable=all,
        --max-connections=1001,
      ]
    ports:
      - 3306:3006
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  primes-nodejs:
    image: ariel17/primes
    container_name: primes
    ports:
      - 8080:8080
