{
 "title": "Prime search process",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Found rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(found{}[$__interval])" }
   ]
  },
  {
   "title": "Not found rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(not_found{}[$__interval])" }
   ]
  },
  {
   "title": "Found vs not found rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "rate(found{}[$__interval])", "legendFormat": "found" },
    { "expr": "rate(not_found{}[$__interval])", "legendFormat": "not found" }
   ]
  },
  {
   "title": "Search time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(search_time{}[$__interval])"
    }
   ]
  }
 ]
}